version: '3.3'

volumes:
  static:
  backend_static:
  backend_media:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    image: antonzemtsov/foodgram-frontend
    volumes:
      - static:/app/result_build/build
  backend:
    image: antonzemtsov/foodgram-backend
    env_file: ../.env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/backend_static
      - backend_media:/backend_media
