# Generated by Django 3.2.3 on 2023-10-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231002_2058'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='check_double_favorite',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='recipes.recipe'),
        ),
    ]
