# Generated by Django 3.2.3 on 2023-09-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'default_related_name': 'ingredients'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags'},
        ),
    ]
